
const Taxa = [
	{name: "Centric", generas: [
		{name: "Acanthoceras"},
		{name: "Actinocyclus"},
		{name: "Aulacoseira"},
		{name: "Brevisira"},
		{name: "Chaetoceros"},
		{name: "Cyclostephanos"},
		{name: "Cyclotella"},
		{name: "Discostella"},
		{name: "Ellerbeckia"},
		{name: "Eupodiscus"},
		{name: "Hydrosera"},
		{name: "Lindavia"},
		{name: "Melosira"},
		{name: "Orthoseira"},
		{name: "Pleurosira"},
		{name: "Pilocaenicus"},
		{name: "Puncticulata"},
		{name: "Skeletonema"},
		{name: "Spicaticribra"},
		{name: "Stephonocyclus"},
		{name: "Stephanodiscus"},
		{name: "Strelnikoviella"},
		{name: "Terpsinoë"},
		{name: "Thalassiosira"},
		{name: "Urosolenia"},]
	},
	{name: "Araphid", generas: [
		{name: "Asterionella"},
		{name: "Ctenophora"},
		{name: "Diatoma"},
		{name: "Diprora"},
		{name: "Distrionella"},
		{name: "Fragilaria"},
		{name: "Fragilariforma"},
		{name: "Hannaea"},
		{name: "Meridion"},
		{name: "Odontidium"},
		{name: "Oxyneis"},
		{name: "Pseudostaurosira"},
		{name: "Pseorostaurosiropsis"},
		{name: "Punctastriata"},
		{name: "Stauroforma"},
		{name: "Staurosira"},
		{name: "Staurosirella"},
		{name: "Synedra"},
		{name: "Tabellaria"},
		{name: "Tabularia"},
		{name: "Tetracyclus"},
		{name: "Tibetiella"},
		{name: "Ulnaria"}]
	},
	
	{name: "Eunotioid", generas: [
		{name: "Actinella"},
		{name: "Amphicampa"},
		{name: "Amphorotia"},
		{name: "Eunotia"},
		{name: "Peronia"},
		{name: "Semiorbis"}]
	},
	
	{name: "Symmetric Biraphid", generas: [
		{name: "Adlafia"},
		{name: "Amphipleura"},
		{name: "Aneumastus"},
		{name: "Anomoeoneis"},
		{name: "Biremis"},
		{name: "Boreozonacola"},
		{name: "Brachysira"},
		{name: "Brevilinea"},
		{name: "Caloneis"},
		{name: "Capartogramma"},
		{name: "Cavinula"},
		{name: "Chamaepinnularia"},
		{name: "Cosmioneis"},
		{name: "Craspedostauros"},
		{name: "Craticula"},
		{name: "Decuassata"},
		{name: "Diadesmis"},
		{name: "Diatomella"},
		{name: "Diploneis"},
		{name: "Envekadea"},
		{name: "Eolimna"},
		{name: "Fallacia"},
		{name: "Fistulifera"},
		{name: "Frickea"},
		{name: "Frustulia"},
		{name: "Geissleria"},
		{name: "Genkalia"},
		{name: "Gyrosigma"},
		{name: "Haslea"},
		{name: "Hippodonta"},
		{name: "Humidophila"},
		{name: "Hygropetra"},
		{name: "Kobayasiella"},
		{name: "Kraskella"},
		{name: "Lacustriella"},
		{name: "Luticola"},
		{name: "Mastogloia"},
		{name: "Mayamaea"},
		{name: "Micrcostatus"},
		{name: "Microfissurata"},
		{name: "Muelleria"},
		{name: "Navicula"},
		{name: "Neidiomorpha"},
		{name: "Neidiopsis"},
		{name: "Neidium"},
		{name: "Nupela"},
		{name: "Parlibellus"},
		{name: "Pinnularia"},
		{name: "Placoneis"},
		{name: "Plagiotropis"},
		{name: "Playaensis"},
		{name: "Pleurosigma"},
		{name: "Prestauroneis"},
		{name: "Pseudofallacia"},
		{name: "Rexlowea"},
		{name: "Scolipleura"},
		{name: "Sellaphora"},
		{name: "Stauroneis"},
		{name: "Staurophora"},]
	},
	
	{name: "Monoraphid", generas: [
		{name: "Achnantes"},
		{name: "Achanthidium"},
		{name: "Anorthoneis"},
		{name: "Cocconeis"},
		{name: "Eucocconeis"},
		{name: "Gliwiczia"},
		{name: "Karayevia"},
		{name: "Lemnicola"},
		{name: "Planothidium"},
		{name: "Platessa"},
		{name: "Psammothidium"},
		{name: "Rossithidium"},]
	},
	{name: "Asymmetric Biraphid", generas: [
		{name: "Afrocymbella"},
		{name: "Amphora"},
		{name: "Brebissonia"},
		{name: "Cymbella"},
		{name: "Cymbopleura"},
		{name: "Delicata"},
		{name: "Didymosphenia"},
		{name: "Encyonema"},
		{name: "Encyonopsis"},
		{name: "Gomphoneis"},
		{name: "Gomphonema"},
		{name: "Gomphosinica"},
		{name: "Gomphosphenia"},
		{name: "Halamphora"},
		{name: "Kurtkrammeria"},
		{name: "Navicymbula"},
		{name: "Oricymba"},
		{name: "Reimeria"},
		{name: "Rhoicosphenia"},]
	},
	{name: "Epithemioid", generas: [
		{name: "Epithemia"},
		{name: "Rhopalodia"}]
	},
	{name: "Nitzschioid", generas: [
		{name: "Bacillaria"},
		{name: "Cylindrotheca"},
		{name: "Cymbellonitzschia"},
		{name: "Denticula"},
		{name: "Grunowia"},
		{name: "Hantzschia"},
		{name: "Nitzchia"},
		{name: "Psammodictyon"},
		{name: "Simonsenia"},
		{name: "Tryblionella"}
	]},
	{name: "Surirelloid", generas: [
		{name: "Campylodiscus"},
		{name: "Cymatopleura"},
		{name: "Entomoneis"},
		{name: "Stenopterobia"},
		{name: "Surirella"}]
	}
]

export default Taxa;
