
const Data =[
	{name: "Centric", generas: [
		{name: "Acanthoceras"},
		{name: "Actinocyclus"},
		{name: "Aulacoseira"},
		{name: "Brevisira"},
		{name: "Chaetoceros"},
		{name: "Cyclostephanos"},
		{name: "Cyclotella"},
		{name: "Discostella"},
		{name: "Ellerbeckia"},
		{name: "Eupodiscus"},
		{name: "Hydrosera"},
		{name: "Lindavia"},
		{name: "Melosira"},
		{name: "Orthoseira"},
		{name: "Pleurosira"},
		{name: "Pilocaenicus"},
		{name: "Puncticulata"},
		{name: "Skeletonema"},
		{name: "Spicaticribra"},
		{name: "Stephonocyclus"},
		{name: "Stephanodiscus"},
		{name: "Strelnikoviella"},
		{name: "Terpsinoë"},
		{name: "Thalassiosira"},
		{name: "Urosolenia"},]
	},
	{name: "Araphid", genera: [
		{name: "Asterionella"},
		{name: "Ctenophora"},
		{name: "Diatoma"},
		{name: "Diprora"},
		{name: "Distrionella"},
		{name: "Fragilaria"},
		{name: "Fragilariforma"},
		{name: "Hannaea"},
		{name: "Meridion"},
		{name: "Odontidium"},
		{name: "Oxyneis"},
		{name: "Pseudostaurosira"},
		{name: "Pseorostaurosiropsis"},
		{name: "Punctastriata"},
		{name: "Stauroforma"},
		{name: "Staurosira"},
		{name: "Staurosirella"},
		{name: "Synedra"},
		{name: "Tabellaria"},
		{name: "Tabularia"},
		{name: "Tetracyclus"},
		{name: "Tibetiella"},
		{name: "Ulnaria"}]
	},
	
	{name: "Eunotioid", genera: [
		{name: "Actinella"},
		{name: "Amphicampa"},
		{name: "Amphorotia"},
		{name: "Eunotia"},
		{name: "Peronia"},
		{name: "Semiorbis"}]
	},
	{name: "Symmetric Biraphid"},
	{name: "Monoraphid"},
	{name: "Asymmetric Biraphid"},
	{name: "Epithemioid"},
	{name: "Nitzschioid"},
	{name: "Surirelloid"}]

export default Data;
